### ISSUE TITLE
Error while running deserialisation for mod-clusterio

### ISSUE THREAD

**Issue by BloodyMikey** [clusterio/clusterio#119] opened 2018-06-24 08:25 UTC
No clue how this happend but is that fixeble?
`  59.971 Error ClientMultiplayerManager.cpp:95: MultiplayerManager failed: multiplayer.cannot-load-downloaded-map("Error while running deserialisation for mod-clusterio: [string "do local _={ticksSinceMasterPinged=0xfp+0,isC..."]:1: function or expression too complex near '"802384732948701238470123"'")
  59.971 Info ClientMultiplayerManager.cpp:573: MapTick(4294967295) changing state from(ConnectedLoadingMap) to(Failed)`

**Comment by Danielv123** [comment] 2018-06-24 10:34
This has happened before, still no idea what the problem is. Since `ticksSinceMasterPinged` is supposed to be set to `0` and not `0xfp+0` I am guessing it might have gotten corrupted in the transport maybe?

The current workaround is to load the save without the clusterio mod (just with normal factorio) and then readding the mod.

**Comment by WilliamRaynaut** [comment] 2018-06-24 17:19
Hi, 
Some friends and I are also consistently getting this bug. It now often takes 10+ tries to get an instance running, and then another 10+ tries to connect to it...

On instance launch (node client.js start instanceName) fails the factorio-current.log says : 
Error ServerMultiplayerManager.cpp:96: MultiplayerManager failed: "Error while running deserialisation for mod-clusterio: [string "do local _={ticksSinceMasterPinged=0x1.cp+4,i..."]:1: function or expression too complex near '"802384732948701238470123"'"

On joining a game, factorio gives error message :
Cannot load downloaded map: Error while running deserialisation for mod-clusterio: [string "do local _={ticksSinceMasterPinged=0x3.9p+4,i..."]:1: function or expression too complex near '"802384732948701238470123"'

This error is not consistent, trying enough times will allow us to start the server or join, but taking half an hour everytime is kind of a pain...

We tried loading the instance save in factorio without the mod, but this obviously destroys everything related to clusterio, and setting up everything again would take hours, which makes this solution impractical...

We tried editing the script.dat file in the saves manually (just changed the value ticksSinceMasterPinged=0xdp+0 to ticksSinceMasterPinged=0 in notepad++), which gives a "corrupted save" error instead. Any way we could do this more cleanly ?


If you need anything else to look into this, we can provide logs or saves. We would really appreciate any fix or workaround for this !
Cheers,

**Comment by WilliamRaynaut** [comment] 2018-06-24 17:43
Ok, this seems to have done the trick for now ! Most of us were just passing the 200 chests and removing a few allows us to load more reliably. Would love to enventually have this 190 chest restriction removed, but for now thanks a lot for the workaround :)

**Comment by Danielv123** [comment] 2018-06-24 18:11
@WilliamRaynaut so, we have been talking about the issue with a dev in the factorio discord server under #mod-making https://i.imgur.com/3F4jguP.png

Could you send the script.dat?

**Comment by Danielv123** [comment] 2018-06-28 22:03
Resolved by clusterio_1.13.1

**Closed as completed by Danielv123** 2018-06-28 22:03 UTC
