### ISSUE TITLE
Install problem ?

### ISSUE THREAD

**Issue by b4xster** [clusterio/clusterio#668] opened 2024-10-27 16:15 UTC
`factorio@b4xnuc:~/clusterio$ npm init "@clusterio"

> npx
> clusteriocreate

? Operating mode to install Standalone (install both controller and host on this computer)
? Admin account name XXXX
? Public DNS/IP address of this server XXXX
? (Linux only) Automatically download latest factorio release? Yes
? Plugins to install
fatal
+------------------------------------------------------------+
| Unexpected error occured installing clusterio, please      |
| report it to https://github.com/clusterio/clusterio/issues |
+------------------------------------------------------------+
TypeError: Cannot read properties of null (reading '0')
    at downloadLinuxServer (/home/factorio/.npm/_npx/860a49d89133e22f/node_modules/@clusterio/create/create.js:718:78)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/home/factorio/.npm/_npx/860a49d89133e22f/node_modules/@clusterio/create/create.js:846:3)

factorio@b4xnuc:~/clusterio$
`
thx for help :/

**Comment by Cooldude2606** [comment] 2024-10-27 16:25
This is caused by the following line, we will look into how the name has been changed for factorio 2.0 and update accordingly.
`const version = filename.match(/(?<=factorio_headless_x64_).*(?=\.tar\.xz)/)[0];`

For now you can answer "no" to downloading the latest stable and install it your self under the factorio dictionary. Ie `clusterio/factorio/2.0.10`

**Comment by Cooldude2606** [comment] 2024-10-27 20:20
Re-openning so we can track that a solution has not been merged into main.

**Closed** 2024-10-27 22:53 UTC
Labels: Factorio 2.0
